openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/phones:
    x-router-controller: phonesController
    get:
      description: Returns all teams
      operationId: getPhones
      responses:
        200:
          description: Team list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/team'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'            
  /api/v1/phones/{year}:
    x-router-controller: phonesController
    get:
      description: Returns a single team by its id
      operationId: findByyear
      parameters:
        - required: true
          name: id
          description: id of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Team found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/team'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    team:
        type: object
        required:
          - id
        properties:
          id:
            type: number
          name:
            type: string
          code:
            type: string
          country:
            type: string
          founded:
            type: number
          national:
            type: boolean
          logo:
            type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true